file 'config/initializers/secret_token.rb' do
  path = Rails.root + 'config' + 'initializers' + 'secret_token.rb'
  secret = SecureRandom.hex(40)
  path.open('w') do |io|
    io.write <<-STRING
# This file was generated by 'rake generate_secret_token', and should
# not be made visible to public.
#
# Your secret key for verifying cookie session data integrity. If you
# change this key, all old sessions will become invalid! Make sure the
# secret is at least 30 characters and all random, no regular words or
# you'll be exposed to dictionary attacks.
PowerdnsOnRails::Application.config.secret_token = '#{secret}'
    STRING
  end
end

desc 'Generates a secret token for the application.'
task :generate_secret_token => ['config/initializers/secret_token.rb']