language: ruby

bundler_args: --without development

rvm:
  - 2.2
  - 2.1
  - 2.0
  - rbx-19mode
  - 1.9.3

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

before_script:
  - mv config/database.yml.template config/database.yml
  - rake generate_secret_token
  - mysql -e 'create database powerdns_test;'
  - psql -c 'create database powerdns_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake db:seed

script: "bundle exec rake ci"

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
    - env: DB=sqlite

sudo: false

notifications:
  webhooks:
    urls:
      -  https://webhooks.gitter.im/e/fd712cc811935fc71415
