# This file was generated by 'rake generate_secret_token', and should
# not be made visible to public.
#
# Your secret key for verifying cookie session data integrity. If you
# change this key, all old sessions will become invalid! Make sure the
# secret is at least 30 characters and all random, no regular words or
# you'll be exposed to dictionary attacks.
PowerdnsOnRails::Application.config.secret_token = '6771c59c2865b12679a4f75cc745886540d4eb54271a7b70c7b8e8a2cb00994cee6cb543b4e4823c'
